### ISSUE TITLE
Does not work in WordPress 6.3 anymore

### ISSUE THREAD

**Issue by chesio** [szepeviktor/auto-login#3]
See: https://core.trac.wordpress.org/changeset/55953 and https://core.trac.wordpress.org/ticket/32510

**Comment by chesio** [comment]
Possible hotfix:
```php
add_action('login_form', function () {
    echo '<script>document.querySelector("form").setAttribute("novalidate", "");</script>';
}, 10, 0);
```

**Comment by szepeviktor** [comment]
I see!
You press the _Log in_ button and the browser displays an error message?

**Comment by szepeviktor** [comment]
> See: https://core.trac.wordpress.org/changeset/55953

@swissspidy You broke the Internet. 🙃 Again!

> Props aznadesign, sanchothefat, alexstine, nant82, **swissspidy**, afercia, d-signed, joedolson.
